services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db

  storage:
    image: redis
    volumes:
      - ./data:/data

  counter:
#    image: kirill000/counter:v1.0.0
    build: ./counter
    restart: always
    volumes:
      - /app/node_modules
      - ./counter:/app
    ports:
      - 3000:3000
    environment:
      - PORTS=3000
      - REDIS_URL=redis://storage
    depends_on:
      - storage

  library-backend:
#    image: kirill000/library:v4.0.0
    build: ./libraryapp/backend
    command: npm run dev
    restart: always
    ports:
      - 3001:3001
    environment:
      - PORTS=3001
      - CNT_PORT=3000
      - REDIS_URL=redis://storage
      - DB_URL=mongodb://root:example@mongo:27017
    volumes:
      - /app/node_modules
      - ./libraryapp/backend:/app
    depends_on:
      - mongo
      - counter
  library-frontend:
    build: ./libraryapp/frontend
    command: npm run dev
    restart: always
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - BASE_URL=http://bookap:3001
      - REDIS_URL=http://counter:3000
    volumes:
      - /app/node_modules
      - ./libraryapp/frontend:/app
    depends_on:
      - counter
      - library-backend